version: "3"
services:
  app:
    container_name: drugstore-backend
    image: jotterkain/drugstore-backend
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        env: ${ENV}
    ports:
      - "3033:3000"
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: postgres
    image: postgres:15.0-alpine
    environment:
      POSTGRES_DB: drugstore
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/drugstore/postgres
    volumes:
      - db:/data/drugstore/postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", '-U', "${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
volumes:
  db: